vscode:
  extensions:
  - aaron-bond.better-comments
  - bungcip.better-toml
  - dcasella.monokai-plusplus
  - esbenp.prettier-vscode
  - formulahendry.auto-close-tag
  - GitHub.vscode-pull-request-github
  - hbenl.test-adapter-converter
  - hbenl.vscode-test-explorer
  - kamikillerto.vscode-colorize
  - pinage404.rust-extension-pack
  - rust-lang.rust-analyzer
  - serayuzgur.crates
  - Swellaby.vscode-rust-test-adapter